{% set version = "0.4.4" %}

package:
  name: pyduktape2
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pyduktape2/pyduktape2-{{ version }}.tar.gz
    sha256: be03478901e28ceefc54eba02c03395152d253663831f83e94b2181e5d5b904c
    patches:
      - 000-no-cython-runtime.patch
  - folder: src
    url: https://github.com/phith0n/pyduktape2/archive/refs/tags/{{ version }}.tar.gz
    sha256: 1408403200c8ff55cdc4e757363243f1727868012e29b7516c8b81657e168884
    patches:
      - 001-no-import-tests.patch

build:
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython <3
    - pip
    - python
  run:
    - python

test:
  source_files:
    - src/tests
  imports:
    - pyduktape2
  commands:
    - pip check
    - cd src/tests && pytest -vv
  requires:
    - pip
    - pytest

about:
  home: https://github.com/phith0n/pyduktape2
  summary: Python integration for the Duktape Javascript interpreter
  license: GPL-2.0-or-later
  license_file:
    - dist/LICENSE.txt
    - dist/COPYRIGHT.txt
    - dist/vendor/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
