{% set version = "0.4.3" %}

package:
  name: pyduktape2
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pyduktape2/pyduktape2-{{ version }}.tar.gz
    sha256: 4444c3c103fd18988b17d22822ac77a8a4c7e602a3122ed3fc93a48732d4f7b2
    patches:
      - 000-no-cython-runtime.patch
  - folder: src
    url: https://github.com/phith0n/pyduktape2/archive/refs/tags/{{ version }}.tar.gz
    sha256: ca4ab4cb216e0e5082f70ec8deccddd77203a1542f71fdcf6a03acbd47629226
    patches:
      - 001-no-import-tests.patch

build:
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  source_files:
    - src/tests
  imports:
    - pyduktape2
  commands:
    - pip check
    - cd src/tests && pytest -vv
  requires:
    - pip
    - pytest

about:
  home: https://github.com/phith0n/pyduktape2
  summary: Python integration for the Duktape Javascript interpreter
  license: GPL-2.0-or-later
  license_file:
    - dist/LICENSE.txt
    - dist/COPYRIGHT.txt
    - dist/vendor/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
