{% set version = "0.4.6" %}
{% if 1 %}
  # TODO: remove after https://github.com/phith0n/pyduktape2/issues/17
  {% set test_version = "0.4.4" %}
{% endif %}

package:
  name: pyduktape2
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pyduktape2/pyduktape2-{{ version }}.tar.gz
    sha256: c84674e202ef4901bca8f6ea8b40197259bf44656167a1106ef076a491421bec
    patches:
      - 000-no-cython-runtime.patch
  - folder: src
    url: https://github.com/phith0n/pyduktape2/archive/refs/tags/{{ test_version }}.tar.gz
    sha256: 1408403200c8ff55cdc4e757363243f1727868012e29b7516c8b81657e168884
    patches:
      - 001-no-import-tests.patch

build:
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - cython <3
    - pip
    - python
  run:
    - python

test:
  source_files:
    - src/tests
  imports:
    - pyduktape2
  commands:
    - pip check
    - cd src/tests
    - coverage run --source=pyduktape2 --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=100
  requires:
    - pip
    - pytest
    - coverage

about:
  home: https://github.com/phith0n/pyduktape2
  summary: Python integration for the Duktape Javascript interpreter
  license: GPL-2.0-or-later
  license_file:
    - dist/LICENSE.txt
    - dist/COPYRIGHT.txt
    - dist/vendor/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
